# Generated by Django 4.2.3 on 2023-07-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
